[project]
name = "demo-styling"
version = "0.1.0"
description = "Course material for app with custom CSS"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "shiny>=1.1.0",
    "shinyswatch>=0.7.0",
]

[tool.uv]
dev-dependencies = [
    "rsconnect-python>=1.24.0",
]
